---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_dbs_custom:
  - name: logs
clickhouse_listen_host:
  - "::"
clickhouse_repo_key: https://packages.clickhouse.com/rpm/stable/repodata/repomd.xml.key
